# Generated by Django 4.2.2 on 2023-06-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_cena_produkt_cena_jednostkowa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(default='-'),
        ),
    ]
