# Generated by Django 4.2.2 on 2023-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_kategoria_options_alter_klient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(),
        ),
    ]
