# Generated by Django 4.2.2 on 2023-06-12 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_produkt_opis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienieszczegoly',
            options={'verbose_name_plural': 'Produkty szczegółowe'},
        ),
        migrations.AlterField(
            model_name='produkt',
            name='cena_jednostkowa',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Minimalna cena to 0 zł')]),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='ilosc_na_magazynie',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Minimalny stan magazynowy to 0')]),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produkty', to='store.kategoria'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='promocje',
            field=models.ManyToManyField(blank=True, to='store.promocja'),
        ),
        migrations.AlterField(
            model_name='zamowienieszczegoly',
            name='produkt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zamowioneprodukty', to='store.produkt'),
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinie', to='store.produkt')),
            ],
        ),
    ]
