# Generated by Django 4.2.2 on 2023-06-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_zamowienieszczegoly_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinia',
            old_name='name',
            new_name='nazwa',
        ),
    ]
