# Generated by Django 4.2.2 on 2023-06-12 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_name_opinia_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koszyk',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
