# Generated by Django 4.2.2 on 2023-06-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_koszyk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koszykszczegoly',
            name='koszyk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='store.koszyk'),
        ),
        migrations.AlterUniqueTogether(
            name='koszykszczegoly',
            unique_together={('koszyk', 'produkt')},
        ),
    ]
