# Generated by Django 4.2.2 on 2023-06-12 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_koszykszczegoly_koszyk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koszykszczegoly',
            name='ilosc',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimalna ilość to 1')]),
        ),
    ]
