# Generated by Django 4.2.2 on 2023-06-12 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_alter_koszykszczegoly_ilosc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name_plural': 'Klienci'},
        ),
        migrations.RemoveIndex(
            model_name='klient',
            name='store_klien_imie_4f5d09_idx',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='klient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
