# Generated by Django 4.2.2 on 2023-06-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_klient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'ordering': ['-id'], 'permissions': [('anuluj zamowienie', 'Może anulować zamówienia')], 'verbose_name_plural': 'Zamówienia'},
        ),
    ]
