# Generated by Django 4.2.2 on 2023-06-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_zamowienie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('zobacz_historie', 'Może zobaczyć historię')], 'verbose_name_plural': 'Klienci'},
        ),
    ]
