# Generated by Django 4.2.2 on 2023-06-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_klient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='data_urodzenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nr_telefonu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
