# Generated by Django 4.2.2 on 2023-06-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_produkttagmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nazwa'], 'verbose_name_plural': 'Tagi'},
        ),
    ]
